// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *mainwnd;
#include <FL/Fl_Input.H>
extern Fl_Input *hostbox;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *resultbox;
#include <FL/Fl_Spinner.H>
extern Fl_Spinner *portbox;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *plotbtn;
extern Fl_Light_Button *streambtn;
#include <FL/Fl_Button.H>
extern Fl_Button *singlebtn;
extern Fl_Light_Button *connectbtn;
extern Fl_Button *quitbt;
extern Fl_Button *savebtn;
extern Fl_Button *clearbtn;
extern Fl_Button *infobtn;
Fl_Double_Window* make_window();
#endif
